spring.application.name=bai4_qlsp

# K?t n?i MySQL (XAMPP m?c ??nh user: root, password tr?ng)
spring.datasource.url=jdbc:mysql://localhost:3306/j2ee_bai05?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# T? ??ng t?o b?ng t? Entity Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# S? d?ng Dialect t??ng thích v?i MySQL c? c?a XAMPP
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect